version: "3"

services:
  # Frontend: Next.js 14
  next_app:
    container_name: next_app
    image: next_app:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://go_api:4000
    depends_on:
      - go_api

  # Backend: Go
  go_api:
    container_name: go_api
    image: go_api:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_PASSWORD=M54NgfzJENBABz3z
      - API_PORT=4000
    depends_on:
      - db

  # Database: MongoDB
  db:
    container_name: mongo_db
    image: mongo:7.0.6
    ports:
      - "27017:27017"
